name: islami
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  audioplayers: ^6.1.1
  bloc: ^9.0.0
  connectivity_plus: ^6.1.2
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_offline: ^4.0.0
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  go_router: ^14.7.1
  intl: ^0.20.2
  persistent_bottom_nav_bar: ^6.2.1
  persistent_bottom_nav_bar_v2: ^5.3.1
  shared_preferences: ^2.4.0
  smooth_page_indicator: ^1.2.0+3
  squiggly_slider: ^1.0.5
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/

  fonts:
    - family: Kamali
      fonts:
        - asset: assets/fonts/Kamali-Personal.ttf
    - family: Janna
      fonts:
        - asset: assets/fonts/Janna-LT-Regular.ttf
    - family: arsura
      fonts:
        - asset: assets/fonts/arsura.ttf
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: digital
      fonts:
        - asset: assets/fonts/digital.ttf

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: assets.dart
